name: "bug"
description: "버그 리포트"
title: "bug: "
labels: ["type:bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## 작성 가이드
        - **Steps to Reproduce**는 번호 목록으로
        - **Expected / Actual**을 분리
        - 가능하면 스크린샷/로그 첨부

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: 버그 요약(사용자 영향도 포함)
      placeholder: "예) 조합 생성 요청이 1500ms 타임박스를 초과하여 500 오류 발생"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: 재현 절차(번호 목록)
      placeholder: |
        1) /api/timetable/generate 호출
        2) requiredCourseCodes=['CS101']로 30회 연속 요청
        3) 10번째 이후 500 응답
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected
      placeholder: "예) 429(레이트리밋) 또는 200 + 캐시 결과"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual
      placeholder: "예) 500 Internal Server Error, 응답 지연 3s"
    validations:
      required: true

  - type: input
    id: env
    attributes:
      label: Environment
      placeholder: "예) local/prod, Java 21, MySQL 8.3, Docker yes/no, 브라우저/OS"
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: 관련 로그/스택트레이스/스크린샷
      placeholder: "예) ERROR ... X-Request-ID=abcd1234"
      render: shell
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options: ["prio:high", "prio:med", "prio:low"]
      default: 0
    validations:
      required: false
